
addEvent("gra.onAclCreate", false)
addEvent("gra.onAclDestroy", false)
addEvent("gra.onAclGroupCreate", false)
addEvent("gra.onAclGroupDestroy", false)
addEvent("gra.onAclRightChange", false)
addEvent("gra.onAclRightRemove", false)
addEvent("gra.onAclGroupACLAdd", false)
addEvent("gra.onAclGroupACLRemove", false)
addEvent("gra.onAclGroupObjectAdd", false)
addEvent("gra.onAclGroupObjectRemove", false)
addEvent("gra.onAclChange", false)
addEvent("gra.onAclAnyChange", false)

local function onAnyChange()
	triggerEvent("gra.onAclAnyChange", root)
end
addEventHandler("gra.onAclCreate", root, onAnyChange, false)
addEventHandler("gra.onAclDestroy", root, onAnyChange, false)
addEventHandler("gra.onAclGroupCreate", root, onAnyChange, false)
addEventHandler("gra.onAclGroupDestroy", root, onAnyChange, false)
addEventHandler("gra.onAclRightChange", root, onAnyChange, false)
addEventHandler("gra.onAclRightRemove", root, onAnyChange, false)
addEventHandler("gra.onAclGroupACLAdd", root, onAnyChange, false)
addEventHandler("gra.onAclGroupACLRemove", root, onAnyChange, false)
addEventHandler("gra.onAclGroupObjectAdd", root, onAnyChange, false)
addEventHandler("gra.onAclGroupObjectRemove", root, onAnyChange, false)
addEventHandler("gra.onAclChange", root, onAnyChange, false)